= Design Documentation

== Test Data Description

Generated test sets are:

* 1e1 (10) transactions
* 1e2 (100) transactions
* 1e3 (1 000) transactions
* 1e4 (10 000) transactions
* 1e5 (100 000) transactions
* 1e6 (1 000 000) transactions


=== Chart of Accounts

Chart of Accounts has 378 entries and it is generated based on txn's dates:

For "assets" following structure is used `a:ay<year>:am<month>`.

This yields to 12 different accounts:

 ...
 "a:ay2016:am01",
 "a:ay2016:am02",
 "a:ay2016:am03",
 ...


For "expenses" following structure is used `e:ey<year>:em<month>:ed<day>`.

This yields to 366 different accounts:

 ...
 "e:ey2016:em01:ed01",
 "e:ey2016:em01:ed02",
 "e:ey2016:em01:ed03",
 ...

The Chart of Accounts is 378 accounts in total.

==== Commodity mode

In `comm` mode the top level accounts `a` and `e` are replaced with `Assets` and `Expenses`, and the first letters of sub-accounts are capitalized. This is done to be as close to beancount as possible.

=== Chart of Commodities

Commodity is selected from this table of 31 commodities

[source,rust]
----
        "CAA", "CAB", "CAC", "CAD", "CAE",
        "CBA", "CBB", "CBC", "CBD", "CBE",
        "CCA", "CCB", "CCC", "CCD", "CCE",
        "CDA", "CDB", "CDC", "CDD", "CDE",
        "CEA", "CEB", "CEC", "CED", "CEE",
        "CFA", "CFB", "CFC", "CFD", "CFE",
        "EUR"
----

based on transaction dates.

=== Examples of Test Transactions

==== Plain Journal

.plain, flavor=tackler
----
2024-01-01 (#0000001) '1E5 txn-1
e:ey2024:em01:ed01  1.0000001
a:ay2024:am01

2024-01-01 (#0000002) '1E5 txn-2
e:ey2024:em01:ed01  1.0000001
a:ay2024:am01
----

.plain, flavor=ledger
[source,text]
----
2024/01/01 (#0000001) 1E5 txn-1
  e:ey2024:em01:ed01  1.0000001
  a:ay2024:am01

2024/01/01 (#0000002) 1E5 txn-2
  e:ey2024:em01:ed01  1.0000001
  a:ay2024:am01
----

==== Journal with Commodities

.comm, flavor=tackler
----
2024-01-01 (#0000001) '1E1 txn-1
  Expenses:Ey2024:Em01:Ed01  1.0000001 CAA
  Assets:Ay2024:Am01

2024-02-06 (#0000002) '1E1 txn-2
  Expenses:Ey2024:Em02:Ed06  6.0000001 CBA
  Assets:Ay2024:Am02
----

.comm, flavor=ledger
----
include ../conf/accounts.ledger

2024/01/01 (#0000001) 1E1 txn-1
  Expenses:Ey2024:Em01:Ed01  1.0000001 CAA
  Assets:Ay2024:Am01

2024/02/06 (#0000002) 1E1 txn-2
  Expenses:Ey2024:Em02:Ed06  6.0000001 CBA
  Assets:Ay2024:Am02
----

.comm, flavor=beancount
----
include "../conf/accounts.beancount"

2024-01-01 * "(#0000001) 1E1 txn-1"
  Expenses:Ey2024:Em01:Ed01  1.0000001 CAA
  Assets:Ay2024:Am01

2024-02-06 * "(#0000002) 1E1 txn-2"
  Expenses:Ey2024:Em02:Ed06  6.0000001 CBA
  Assets:Ay2024:Am02
----

==== Test Data for Tackler's Audit Mode

.audit, flavor=tackler
[source,text]
----
2024-01-01T00:00:00+00:00 (#0000001) '1E1 txn-1
  # uuid: 73fce96a-a16a-51e2-9948-ec9c51a80ff4
  e:ey2024:em01:ed01  1.0000001
  a:ay2024:am01

2024-02-06T14:24:00+00:00 (#0000002) '1E1 txn-2
  # uuid: fb4be4b6-2e2d-5af2-bb84-68c5ba8b52d5
  e:ey2024:em02:ed06  6.0000001
  a:ay2024:am02
----


== Journal

=== Single File Mode

The transactions are stored in single file (one journal).

=== Shard by Month

Transactions are sharded based on txn dates, so that each journal contains one month data
`set-1e5-month/txns/YYYY-MM.txn`.

The journal is the top of shard tree, e.g. `set-1e5-month/txns` in above example.


=== Shard by TXN

Each transaction is located on own file, and sharding of transactions is based on txn dates,
e.g. one transaction would be  `set-1e6-txn/txns/YYYY/MM/DD/YYYYMMDDTHHMMSS-idx.txn`,
where `idx` is index of txn for txns-1e6 test set.

The journal is the top of shard tree, e.g. `set-1e6-txn/txns` in above example.


=== Audit Mode: txn UUID

Some integration tests need a stable set of unique txn UUIDs
This test tool will generate these kind of UUIDs.
In real life use, just normal random UUID is suitable for txn uuid.

The UUID is V5 with URL namespace and the used url is:
`pta-generator:/<set>/<number>/<ts>[/<spec>]`
where `ts` is timestamp in RFC 3339 format,
and `spec` is free, optional specifier, e.g. `audit`.


== Extending With New Journal Types

See `generators.rs` Traits, `commands::comm.rs` and `commands::plain.rs` as an example how to extend the pta-generator with new journal type generator or journal type (e.g. `complex`).
