
name: ci

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check -- --style-edition 2024

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --no-deps -- -D warnings
  
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
 
